### ISSUE TITLE
Parameter loading issue with "MoveIt Quickstart in RViz" on Rolling

### ISSUE THREAD

**Issue by destogl** [ros-planning/moveit2_tutorials#303]
### Description

Issues with loading parameters in rolling 

### Your environment
* ROS Distro: Rolling and Galactic
* OS Version: Ubuntu 20.04
* Source build
* workspace state (should be the same as defined in `moveit2_tutorials.repos` file)
  ```
  repositories:
    geometric_shapes:
      type: git
      url: https://github.com/ros-planning/geometric_shapes
      version: 6b37f6885f1a4d264087b978a7965fb2c8d72c3b
    moveit2:
      type: git
      url: https://github.com/ros-planning/moveit2
      version: c8d3b19da0b902c2ac2ab6791bcd5891bebcc505
    moveit2_tutorials:
      type: git
      url: git@github.com:ros-planning/moveit2_tutorials.git
      version: 6aae45f539b0a797562c82bd80d87ef002827680
    moveit_msgs:
      type: git
      url: https://github.com/ros-planning/moveit_msgs
      version: 989674b94de3dbe4401adb28de49aa4cbd069826
    moveit_visual_tools:
      type: git
      url: https://github.com/ros-planning/moveit_visual_tools
      version: cef60e3328c83d7df0cab0b02e53bca2779655b4
    ros2_control:
      type: git
      url: git@github.com:ros-controls/ros2_control.git
      version: 407bbd1066dae25f6da8e3422dfa1a10118c791f
    ros2_controllers:
      type: git
      url: git@github.com:ros-controls/ros2_controllers.git
      version: d5d24d90615844f04a59a187732adec3aa4efae0
    rviz_visual_tools:
      type: git
      url: https://github.com/PickNikRobotics/rviz_visual_tools.git
      version: 445b998c658ea91cf220e79bd9ef3b3495a5f3da
  ```

### Steps to reproduce
Try starting ["MoveIt Quickstart in RViz" tutorial](https://moveit.picknik.ai/galactic/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html)

When "MotionPlanning" plugin is added following output comes out in terminal and robot is not shown as described:

```
[rviz2-1] [ERROR] [1642267958.594784654] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-1] [INFO] [1642267958.643654296] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0021203 seconds
[rviz2-1] [INFO] [1642267958.643718636] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] [ERROR] [1642267958.650450666] [moveit_background_processing.background_processing]: Exception caught while processing action 'loadRobotModel': parameter 'panda_arm.kinematics_solver_timeout' has invalid type: Wrong parameter type, parameter {panda_arm.kinematics_solver_timeout} is of type {double}, setting it to {string} is not allowed.
```

### Expected behavior
Panda robot should be shown in simulation.
